### ISSUE TITLE
ModuleNotFoundError: No module named 'General'

### ISSUE THREAD

**Issue by Sam-Sims** [lipan6461188/icSHAPE-pipe#2]
Hello,

When running icSHAPE-pipe evaluateSHAPE

I get the following traceback

```
traceback (most recent call last):
  File "/gpfs/home/naa17jnu/scratch/scripts/icSHAPE-pipe/bin/Functions/evaluateSHAPE.py", line 14, in <module>
    import General, Structure
ModuleNotFoundError: No module named 'General'
```
Thanks,
Sam

**Comment by noahpieta** [comment]
+1, i have the same issue.

**Comment by noahpieta** [comment]
I found how to solve it. the two packages come from the IPyRSSA package. 
https://github.com/lipan6461188/IPyRSSA.git 

just copy the General.py, Structure.py and Color.py to icSHAPE-pipe/bin/Functions
